
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.bootiful.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-20T16:30:43.862+03:00
 * Generated source version: 3.1.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "BootifulWSImplService",
                      portName = "BootifulWSImplPort",
                      targetNamespace = "http://ws.bootiful.com/",
                      wsdlLocation = "file:/C:/Workspace-Intellij/Bootiful/client/src/main/resources/BootifulWS.wsdl",
                      endpointInterface = "com.bootiful.ws.BootifulWS")
                      
public class BootifulWSImplPortImpl implements BootifulWS {

    private static final Logger LOG = Logger.getLogger(BootifulWSImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.bootiful.ws.BootifulWS#users()*
     */
    public java.util.List<com.bootiful.ws.User> users() { 
        LOG.info("Executing operation users");
        try {
            java.util.List<com.bootiful.ws.User> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
