package com.bootiful.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-20T16:30:43.899+03:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "BootifulWSImplService", 
                  wsdlLocation = "file:/C:/Workspace-Intellij/Bootiful/client/src/main/resources/BootifulWS.wsdl",
                  targetNamespace = "http://ws.bootiful.com/") 
public class BootifulWSImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.bootiful.com/", "BootifulWSImplService");
    public final static QName BootifulWSImplPort = new QName("http://ws.bootiful.com/", "BootifulWSImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Workspace-Intellij/Bootiful/client/src/main/resources/BootifulWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BootifulWSImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Workspace-Intellij/Bootiful/client/src/main/resources/BootifulWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BootifulWSImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BootifulWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BootifulWSImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BootifulWSImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BootifulWSImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BootifulWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BootifulWS
     */
    @WebEndpoint(name = "BootifulWSImplPort")
    public BootifulWS getBootifulWSImplPort() {
        return super.getPort(BootifulWSImplPort, BootifulWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BootifulWS
     */
    @WebEndpoint(name = "BootifulWSImplPort")
    public BootifulWS getBootifulWSImplPort(WebServiceFeature... features) {
        return super.getPort(BootifulWSImplPort, BootifulWS.class, features);
    }

}
